Allow to load file directly into the VFS
nrc/rls-vfs pull request #10
Opened 2017-01-18 09:37 UTC by matklad

This is the scaled down version of https://github.com/nrc/rls-vfs/pull/7. 

Does this look reasonable? I'll update RSL as well if this is OK :) 

PS: am I correct that we don't use `rustfmt` for this repository yet?

2017-01-18 20:30 UTC, nrc requested changes
LGTM, thanks! Just a couple of nits to address

2017-01-18 20:30 UTC, nrc commented on src/lib.rs
> +    Replace {
Maybe ReplaceText for symmetry with AddFile

2017-01-18 20:30 UTC, nrc commented on src/lib.rs
> +            // XXX: if the first change is `Add`, we should avoid loading
Could you file an issue for this and s/XXX/FIXME(#...)

2017-01-19 09:22 UTC, matklad commented
Nits fixed, here's the RLS PR: https://github.com/jonathandturner/rls/pull/148

2017-01-19 19:39 UTC, merged

2017-01-19 19:40 UTC, nrc commented
Great, thank you!